// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Artist struct {
	ID   string
	Name string
}

type Play struct {
	PlayedAtMs int64
	TrackID    string
	ContextUri sql.NullString
}

type Track struct {
	ID         string
	Name       string
	AlbumName  string
	DurationMs int64
}

type TrackArtist struct {
	TrackID  string
	ArtistID string
	Position int64
}
