// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plays.sql

package db

import (
	"context"
	"database/sql"
)

const deleteTrackArtists = `-- name: DeleteTrackArtists :exec
DELETE FROM track_artists WHERE track_id = ?
`

func (q *Queries) DeleteTrackArtists(ctx context.Context, trackID string) error {
	_, err := q.db.ExecContext(ctx, deleteTrackArtists, trackID)
	return err
}

const insertPlay = `-- name: InsertPlay :execrows
INSERT INTO plays (played_at_ms, track_id, context_uri)
VALUES (?, ?, ?)
ON CONFLICT (played_at_ms) DO NOTHING
`

type InsertPlayParams struct {
	PlayedAtMs int64
	TrackID    string
	ContextUri sql.NullString
}

func (q *Queries) InsertPlay(ctx context.Context, arg InsertPlayParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertPlay, arg.PlayedAtMs, arg.TrackID, arg.ContextUri)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const latestPlayedAt = `-- name: LatestPlayedAt :one
SELECT CAST(COALESCE(MAX(played_at_ms), 0) AS INTEGER) AS played_at_ms FROM plays
`

func (q *Queries) LatestPlayedAt(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, latestPlayedAt)
	var played_at_ms int64
	err := row.Scan(&played_at_ms)
	return played_at_ms, err
}

const upsertArtist = `-- name: UpsertArtist :exec
INSERT INTO artists (id, name)
VALUES (?, ?)
ON CONFLICT (id) DO UPDATE SET
    name = excluded.name
`

type UpsertArtistParams struct {
	ID   string
	Name string
}

func (q *Queries) UpsertArtist(ctx context.Context, arg UpsertArtistParams) error {
	_, err := q.db.ExecContext(ctx, upsertArtist, arg.ID, arg.Name)
	return err
}

const upsertTrack = `-- name: UpsertTrack :exec
INSERT INTO tracks (id, name, album_name, duration_ms)
VALUES (?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    name = excluded.name,
    album_name = excluded.album_name,
    duration_ms = excluded.duration_ms
`

type UpsertTrackParams struct {
	ID         string
	Name       string
	AlbumName  string
	DurationMs int64
}

func (q *Queries) UpsertTrack(ctx context.Context, arg UpsertTrackParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrack,
		arg.ID,
		arg.Name,
		arg.AlbumName,
		arg.DurationMs,
	)
	return err
}

const upsertTrackArtist = `-- name: UpsertTrackArtist :exec
INSERT INTO track_artists (track_id, artist_id, position)
VALUES (?, ?, ?)
ON CONFLICT (track_id, artist_id) DO UPDATE SET
    position = excluded.position
`

type UpsertTrackArtistParams struct {
	TrackID  string
	ArtistID string
	Position int64
}

func (q *Queries) UpsertTrackArtist(ctx context.Context, arg UpsertTrackArtistParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrackArtist, arg.TrackID, arg.ArtistID, arg.Position)
	return err
}
