// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	DeleteTrackArtists(ctx context.Context, trackID string) error
	InsertPlay(ctx context.Context, arg InsertPlayParams) (int64, error)
	LatestPlayedAt(ctx context.Context) (int64, error)
	UpsertArtist(ctx context.Context, arg UpsertArtistParams) error
	UpsertTrack(ctx context.Context, arg UpsertTrackParams) error
	UpsertTrackArtist(ctx context.Context, arg UpsertTrackArtistParams) error
}

var _ Querier = (*Queries)(nil)
